service: publish-power-consumption-to-ha

plugins:
  - serverless-python-requirements
  - serverless-prune-plugin

custom:
  sqsQueueName: csv-object-created
  prune:
    automatic: true
    number: 3

provider:
  name: aws
  runtime: python3.12
  stage: ${opt:stage, 'dev'}
  region: eu-west-3
  deploymentBucket:
    name: sls-deployments-${aws:accountId}-${self:provider.region}
    maxPreviousDeploymentArtifacts: 1
  environment:
    HA_TOKEN: ${env:HA_TOKEN}
    HA_URL: ${env:HA_URL}
    LOG_LEVEL: INFO
    MONTHS: ${env:MONTHS}
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:GetObject"
        - "s3:GetObjectVersion"
      Resource:
        - "arn:aws:s3:::riblup-home-management/*"
    - Effect: "Allow"
      Action:
        - "sqs:DeleteMessage"
        - "sqs:ReceiveMessage"
        - "sqs:SendMessage"
        - "sqs:GetQueueAttributes"
      Resource:
        - "arn:aws:sqs:${aws:region}:${aws:accountId}:${self:custom.sqsQueueName}"

functions:
  run:
    handler: handler.run
    description: Pushes power consumption data into Home Assistant.
    timeout: 30
    events:
      - sqs:
          arn: "arn:aws:sqs:${aws:region}:${aws:accountId}:${self:custom.sqsQueueName}"
          batchSize: 1
