name: Serverless Deploy

on:
  push:
    branches:
      - main

jobs:
  sls-deploy:
    name: Serverless Deploy
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ github.workspace }}/serverless/
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - name: Git Checkout
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - run: npm shrinkwrap

      - run: npm ci

      - name: serverless install plugins
        uses: serverless/github-action@v3.2
        with:
          args: |
            -c "
            cd ./serverless &&
            serverless plugin install --name serverless-python-requirements &&
            serverless plugin install --name serverless-prune-plugin
            "
          entrypoint: /bin/sh

      - name: serverless deploy
        uses: serverless/github-action@v3.2
        with:
          args: -c "cd ./serverless && serverless deploy --stage ${{ env.CI_ENV }} --verbose"
          entrypoint: /bin/sh
        env:
          CI_ENV: prod
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          HA_TOKEN: ${{ secrets.HA_TOKEN }}
          HA_URL: ${{ secrets.HA_URL }}
          MONTHS: ${{ vars.MONTHS }}
