name: Remove AWS services

on: workflow_dispatch

jobs:
  sls-remove-prod:
    name: Serverless Remove Prod
    runs-on: ubuntu-latest
    environment:
      name: production
    strategy:
      matrix:
        node-version: [18.x]
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm shrinkwrap
    - run: npm ci
    - name: serverless remove
      uses: serverless/github-action@v3.2
      with:
        args: remove
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}